// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Note is the predicate function for note builders.
type Note func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
